### ISSUE TITLE
[macOS] Is It Possible To Have Multiple Effect In One Window?

### ISSUE THREAD

**Issue by meike02** [alexmercerind/flutter_acrylic#36]
Since macOS window's color could change with desktop background, is it possible or is there a workaround to have multiple effect on one window? Like the Email app or Apple Music app on macOS?

<img width="1049" alt="截屏2022-10-01 00 13 25" src="https://user-images.githubusercontent.com/61854819/193314008-f171fccf-f2ed-4207-a3a2-c6144c7117de.png">

<img width="1041" alt="截屏2022-10-01 00 13 41" src="https://user-images.githubusercontent.com/61854819/193314049-2a72f9db-ca9f-449d-b5cf-e504eed3e29f.png">

**Comment by Adrian-Samoticha** [comment]
Such functionality is not supported at the moment. I'm currently not quite sure what's the best way to implement it, though.
I wanted to check how [macos_ui](https://pub.dev/packages/macos_ui) goes about solving this issue, however, it turns out that it does, in fact, not support window tinting either.

One way would be to add support for adding multiple [`NSVisualEffectView`](https://developer.apple.com/documentation/appkit/nsvisualeffectview)s to _flutter_acrylic_ and implement a way to manipulate them through Dart code.

Another way would be to find a way to retrieve the current wallpaper and window position and implement the window tinting yourself. While the window position can be retrieved using [window_utils](https://pub.dev/documentation/window_utils/latest/), I have not found a package that allows you to retrieve the system's desktop wallpaper. Perhaps that could be done via the [wallpaper](https://crates.io/crates/wallpaper) crate and Dart/Rust ffi, though?

I'd have to do a little bit of research to find out what's the best way forward.

**Comment by Adrian-Samoticha** [comment]
Turns out that macOS asks the user for permission when a program attempts to retrieve the current wallpaper using the [wallpaper](https://crates.io/crates/wallpaper) crate which might make it less than ideal for this specific use case.

**Comment by meike02** [comment]
Alright, thanks for answering! And thanks for all the works that you did!

**Comment by Adrian-Samoticha** [comment]
No problem. I am currently a little busy with some personal matters, but I'll look further into this issue once I'm free.

**Comment by Adrian-Samoticha** [comment]
I managed to add two [`NSVisualEffectView`](https://developer.apple.com/documentation/appkit/nsvisualeffectview)s to a single window and it now looks like this:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/86920182/197199254-ddac5e92-39da-4955-b748-2e1fc5a3db85.png">

There are still certain issues with this implementation (such as the transparent subview blocking mouse events) but given that what we're after seems very much possible I guess I'd assign myself. :)

**Comment by Adrian-Samoticha** [comment]
Alright, I am now able to manipulate the views through Dart code, and the performance is pretty good as well. I am manipulating the view 125 times per second right here:

https://user-images.githubusercontent.com/86920182/197355337-887118dd-7f3f-44ca-a8fd-dd544b954e57.mov

This means that animations are very well possible. Also, the alpha value of the views can also be changed, so applying them to pop-up windows and the like (which may change their transparency during the open/close animations) is all fair game. :D

Things are certainly going well.

**Comment by meike02** [comment]
OMG, that's fantastic!!! Thanks sososososososososo much!!!! 🥳🥳🥳🥳🥳

**Comment by meike02** [comment]
That's so amazing!!!!! When my app is accomplished you'll be the FIRST ONE on the thank list!!!!! 😘😘😘😘😘😘

**Comment by jinfagang** [comment]
@Adrian-Samoticha does this merged? this is exactly I need, does it support windows as well BTW?

**Comment by Adrian-Samoticha** [comment]
> @Adrian-Samoticha does this merged? this is exactly I need, does it support windows as well BTW?

This feature has been present in flutter_acrylic for a while now and is fully functional on macOS. Windows doesn't have wallpaper tinting, so I'm not sure how useful this feature would be on Windows. Judging by your recent issue (#60) what you're after is simply an opaque window with a transparent sidebar, though. You could achieve that by setting the material to `WindowEffect.acrylic` and wrapping your content view with a container that has an opaque background, though.

**Comment by jinfagang** [comment]
@Adrian-Samoticha I tried wrapping content in white background, but takes no effect.

**Comment by Adrian-Samoticha** [comment]
@jinfagang Can you show me your code and a screenshot of what you are seeing? If you remember [this post of mine](https://github.com/alexmercerind/flutter_acrylic/issues/32#issuecomment-1179770809), this is basically would you'd need to do on Windows.
