### ISSUE TITLE
Evolution to Linux Application

### ISSUE THREAD

**Issue by gaetan1903** [alexmercerind/flutter_acrylic#4]
Is possible to have use it on Linux ? 

Kde and picom compositor have blur background on Linux.

Thanks

**Comment by alexmercerind** [comment]
Hello, I've been trying to get it to work on Linux. I'll defintely see how I can get it working.
Since, Flutter window on Linux currently uses GTK 3.0, I didn't find a way yet.

I could only make the window transparent.
![Screenshot from 2021-06-25 16-31-09](https://user-images.githubusercontent.com/28951144/123415410-d64ab200-d5d2-11eb-8dc9-fb8a54184b03.png)

**Comment by alexmercerind** [comment]
@gaetan1903 


![Screenshot_20210727_014351](https://user-images.githubusercontent.com/28951144/127053239-b47562e5-76f6-4e1e-964e-1e863eb1c1c6.png)

**Comment by gaetan1903** [comment]
GG 
Awesome 💯  

Can you explain? 
How it works on gtk3 ?

**Comment by alexmercerind** [comment]
@gaetan1903 
I have updated the README with answers to your questions, closing this issue.
Thankyou.
