### ISSUE TITLE
Moving window huge delay

### ISSUE THREAD

**Issue by jstnw10** [alexmercerind/flutter_acrylic#6]
First of all: Thanks for the nice package!

I have a little problem. When I use `AcrylicEffect.acrylic`, moving the window behaves lagging and with a huge delay. See the video.

I am on latest master channel and I am using the same setup like the one in the example for `bitsdojo_window` .

https://user-images.githubusercontent.com/40317787/126301399-c92410ae-7f9c-476b-b469-74245d66580e.mp4

**Comment by alexmercerind** [comment]
Hi @jstnw10 !

I'm aware of this issue, this is a bug in Windows 10 itself, all Windows versions higher or equal to 1903 are experiencing this lag.
**This bug however is fixed by Microsoft in Windows 11.** Until then you have to use `AcrylicEffect.aero`, or make effect disabled while window is being dragged.
I have already mentioned this in the README [here](https://github.com/alexmercerind/flutter_acrylic#notes).
