### ISSUE TITLE
Usage of `macos_window_utils` broken in 1.1.1

### ISSUE THREAD

**Issue by ricardoboss** [alexmercerind/flutter_acrylic#66]
Hi! When building an app that uses flutter_acrylic, I get these errors during build:

![image](https://user-images.githubusercontent.com/6266356/222002713-b2cd84a9-a1cf-4df8-a074-4db5a477abe5.png)

This looks like either an error in the latest version of macos_window_utils' exports or in the usages of it in this repo.

**Comment by ricardoboss** [comment]
As a workaround: downgrade to `1.0.0+2`

**Comment by Adrian-Samoticha** [comment]
Thanks for your report. I have been able to reproduce it on my end. Another possible workaround is to install `macos_window_utils: 1.0.2` if you wished to remain on a more recent version. I am still investigating the issue as we speak.

**Comment by Adrian-Samoticha** [comment]
I believe the issue is now resolved. It was caused by an accidental breaking change in macos_window_utils 1.1.0. I have retracted that version and released a hotfix.

**Comment by ricardoboss** [comment]
I tried your workaround, but now I am getting this error:

```
error: compiling for macOS 10.14, but module 'macos_window_utils' has a minimum deployment target of macOS 10.14.6
```

As the migration guide states, I have changed my Podfile to say: `platform :osx, '10.14.6'`.

What version does the hotfix have?

**Comment by Adrian-Samoticha** [comment]
The minimum deployment target in the Podfile has been 10.14.6 since macos_window_utils' very beginning (though it was lower back when flutter_acrylic was standalone). What's interesting is that the macOS Deployment Target in the flutter_acrylic example project is set to 10.14 and yet compiles fine on my end:

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/86920182/222123794-cfb1fd2c-a12f-4ee8-9501-6760d405e5eb.png">

Either way, could you maybe try setting it to 10.14.6 or above (as described in the readme) and see if that resolves the issue?

Also, try setting **Runner > Build Settings > Deployment > macOS Deployment Target** to 10.14.6 or above as well:
<img width="1440" alt="Screenshot 2023-03-01 at 12 22 21" src="https://user-images.githubusercontent.com/86920182/222125903-eded4c1a-93d5-441f-9b8f-6c39355cb290.png">

**Comment by ricardoboss** [comment]
Ah thanks! That fixed it for me. My bad, I didn't update the minimum target in the xcode project, just in the Podfile.

Feel free to close this issue.
